apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-v1
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    cert-manager.io/issue-temporary-certificate: "true"
spec:
  tls:
    - hosts: 
        - nginx.mogki.com
      secretName: nginx-mogki-se
  rules:
    - host: nginx.mogki.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-v1
                port:
                  number: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo
      tier: app
      version: v1
  template:
    metadata:
      labels:
        app: echo
        tier: app
        version: v1
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
          - containerPort: 80
          imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-v1
spec:
  ports:
    - port: 80
      protocol: TCP
  selector:
    app: nginx
    tier: app
    version: v1